author: alrik94
database: false
description: Logs chat and commands
main: me.alrik94.plugins.cclogger.CCLogger
name: CCLogger
api-version: 1.13
startup: postworld
version: '3.2.1'
permissions:
  cclogger.notify:
    description: Players with this permission get notified when a player says anything on the chat or command notify list.
    default: op
  cclogger.exempt:
    description: Players with this permission do not get logged for anything.
    default: false
commands:
  ccreload:
    description: This command reloads the CCLogger configuration.
    usage: /<command>
    permission: cclogger.reload
    permission-message: You don't have permission to use this command!
  ccl:
    description: This is a base command for many CCLogger commands.
    usage: /<command> <subcommand>
    permission: cclogger.statistics
    permission-message: You don't have permission to use this command!